# Site settings
title: CmoaToto (dot) com
email: antonin.fouques@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    CmoaToto's new world
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cmoatoto.com" # the base hostname & protocol for your site
twitter_username: CmoaToto
github_username:  CmoaToto

# Build settings
markdown: kramdown
